// packages/bakeoff1/src/routes/editor/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import type { PageData } from './$types';

  let { data }: { data: PageData } = $props();
  type ResumeSection = NonNullable<PageData['resume']>['sections'][number];

  const mode = $derived(data.mode);

  let draftTitle = $state('Untitled Resume');
  let draftSummary = $state('');
  let sections = $state<ResumeSection[]>([]);
  let nextTempBulletId = $state(-1);
  let saveState = $state<'idle' | 'saving' | 'saved' | 'error'>('idle');
  let savedMessageTimer: ReturnType<typeof setTimeout> | null = null;

  $effect(() => {
    draftTitle = data.resume?.title ?? 'Untitled Resume';
    draftSummary = data.resume?.summary ?? '';
    sections = (data.resume?.sections ?? []).map((section) => ({
      ...section,
      items: section.items.map((item) => ({
        ...item,
        label: item.label ?? '',
        value: item.value ?? '',
        start_date: item.start_date ?? '',
        end_date: item.end_date ?? '',
        location: item.location ?? '',
        description: item.description ?? '',
      })),
      bullets: [...section.bullets],
    }));
  });

  function addBullet(sectionId: number) {
    sections = sections.map((section) =>
      section.id === sectionId
        ? {
            ...section,
            bullets: [
              ...section.bullets,
              {
                id: nextTempBulletId--,
                section_id: sectionId,
                content: '',
                item_order: section.bullets.length,
              },
            ],
          }
        : section
    );
  }

  function removeBullet(sectionId: number, bulletId: number) {
    sections = sections.map((section) =>
      section.id === sectionId
        ? {
            ...section,
            bullets: section.bullets.filter((bullet) => bullet.id !== bulletId),
          }
        : section
    );
  }

  function serializeSections(payloadSections: ResumeSection[]) {
    return JSON.stringify(
      payloadSections.map((section, sectionIndex) => ({
        id: section.id,
        items: section.items.map((item, itemIndex) => ({
          ...item,
          item_order: itemIndex,
        })),
        bullets: section.bullets.map((bullet, bulletIndex) => ({
          ...bullet,
          item_order: bulletIndex,
        })),
        item_order: sectionIndex,
      }))
    );
  }

  function handleEnhance() {
    saveState = 'saving';
    return async ({
      result,
      update,
    }: {
      result: { type: string };
      update: () => Promise<void>;
    }) => {
      if (result.type === 'success') {
        await update();
        saveState = 'saved';
        if (savedMessageTimer) clearTimeout(savedMessageTimer);
        savedMessageTimer = setTimeout(() => {
          saveState = 'idle';
        }, 2500);
        return;
      }

      saveState = 'error';
    };
  }
</script>

<main class="editor-page">
  <div class="editor-topbar">
    <p class="mode">
      {mode === 'edit' ? `Editing Resume #${data.resume?.id ?? ''}` : 'New Resume'}
    </p>
    <div class="topbar-actions">
      <button type="button" class="action">Preview</button>
      <button type="submit" class="action" form="resume-save-form">
        {saveState === 'saving' ? 'Saving...' : 'Save'}
      </button>
      {#if saveState === 'saved'}
        <span class="save-indicator" role="status" aria-live="polite">Saved</span>
      {:else if saveState === 'error'}
        <span class="save-indicator error" role="alert">Save failed</span>
      {/if}
    </div>
  </div>

  {#if mode === 'edit' && data.resume}
    <form id="resume-save-form" method="POST" action="?/save" use:enhance={handleEnhance}>
      <input type="hidden" name="resumeId" value={data.resume.id} />
      <input type="hidden" name="sections" value={serializeSections(sections)} />
      <article class="resume-sheet" aria-label="Resume editor">
        <header class="sheet-header">
          <input
            class="resume-title"
            bind:value={draftTitle}
            name="title"
            aria-label="Resume title"
          />
          <p class="sub-meta">Candidate profile for tailoring • User {data.resume.userId}</p>
        </header>

        <section class="summary" aria-label="Professional summary">
          <h2>Professional Summary</h2>
          <textarea
            bind:value={draftSummary}
            name="summary"
            rows="4"
            placeholder="Add a concise summary tailored to the role"
          ></textarea>
        </section>

        <section class="resume-sections" aria-label="Resume sections">
          {#each sections as section, sectionIndex (section.id)}
            <section class="resume-section">
              <header class="section-header">
                <h2>{section.title}</h2>
                <span>{section.type ?? 'Section'}</span>
              </header>

              {#if section.items.length > 0}
                <div class="entries">
                  {#each section.items as item, itemIndex (item.id)}
                    <article class="entry-row">
                      <div class="entry-head">
                        <input
                          bind:value={sections[sectionIndex].items[itemIndex].label}
                          aria-label="Entry label"
                          placeholder="Role or degree"
                        />
                        <input
                          bind:value={sections[sectionIndex].items[itemIndex].value}
                          aria-label="Entry value"
                          placeholder="Company or school"
                        />
                      </div>
                      <div class="entry-meta">
                        <input
                          bind:value={sections[sectionIndex].items[itemIndex].start_date}
                          aria-label="Start date"
                          placeholder="Start"
                        />
                        <input
                          bind:value={sections[sectionIndex].items[itemIndex].end_date}
                          aria-label="End date"
                          placeholder="End"
                        />
                        <input
                          bind:value={sections[sectionIndex].items[itemIndex].location}
                          aria-label="Location"
                          placeholder="Location"
                        />
                      </div>
                      <textarea
                        bind:value={sections[sectionIndex].items[itemIndex].description}
                        rows="2"
                        aria-label="Entry description"
                        placeholder="Scope and impact"
                      ></textarea>
                    </article>
                  {/each}
                </div>
              {/if}

              <div class="bullets">
                {#if section.bullets.length > 0}
                  {#each section.bullets as bullet, bulletIndex (bullet.id)}
                    <div class="bullet-line">
                      <span class="marker" aria-hidden="true">•</span>
                      <input
                        bind:value={sections[sectionIndex].bullets[bulletIndex].content}
                        aria-label="Bullet point"
                        placeholder="Achievement bullet"
                      />
                      <button
                        class="remove-bullet"
                        type="button"
                        aria-label="Remove bullet"
                        title="Remove bullet"
                        onclick={() => removeBullet(section.id, bullet.id)}
                      >
                        &minus;
                      </button>
                    </div>
                  {/each}
                {:else}
                  <p class="empty">No bullet points yet.</p>
                {/if}

                <button class="add-bullet" type="button" onclick={() => addBullet(section.id)}>
                  + Add bullet point
                </button>
              </div>
            </section>
          {/each}
        </section>
      </article>
    </form>
  {:else}
    <section class="empty-state">
      <h1>Start a New Resume</h1>
      <p>Load a resume from the dashboard or create a new one to begin tailoring.</p>
      <button type="button" class="action">Create Resume</button>
    </section>
  {/if}
</main>

<style>
  .editor-page {
    --paper: #fff;
    --bg: #f4f0e8;
    --ink: #1f1b15;
    --muted: #6c6154;
    --line: #ddd3c5;
    --accent: #0f6f63;

    min-height: calc(100vh - 12rem);
    background: linear-gradient(180deg, #f8f5ef 0%, #f2ece2 100%);
    padding: 1.25rem;
  }

  .editor-topbar {
    max-width: 860px;
    margin: 0 auto 0.9rem;
    display: flex;
    align-items: center;
    justify-content: space-between;
  }

  .mode {
    margin: 0;
    color: var(--muted);
    font-size: 0.9rem;
  }

  .topbar-actions {
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }

  .action {
    border: 1px solid #d2c6b7;
    background: #fff;
    border-radius: 999px;
    padding: 0.35rem 0.75rem;
    font-size: 0.85rem;
  }

  .save-indicator {
    color: var(--accent);
    font-size: 0.85rem;
    font-weight: 600;
  }

  .save-indicator.error {
    color: #b42318;
  }

  .resume-sheet {
    max-width: 860px;
    margin: 0 auto;
    background: var(--paper);
    border: 1px solid var(--line);
    border-radius: 10px;
    box-shadow: 0 18px 40px rgb(31 27 21 / 10%);
    padding: 2rem 2.2rem;
  }

  .sheet-header {
    border-bottom: 1px solid var(--line);
    padding-bottom: 0.8rem;
  }

  .resume-title {
    width: 100%;
    border: none;
    background: transparent;
    color: var(--ink);
    font-family: var(--font-heading);
    font-size: clamp(1.8rem, 3vw, 2.3rem);
    font-weight: 650;
    padding: 0;
  }

  .resume-title:focus {
    outline: none;
  }

  .sub-meta {
    margin: 0.3rem 0 0;
    color: var(--muted);
    font-size: 0.9rem;
  }

  .summary,
  .resume-section {
    margin-top: 1.2rem;
  }

  h2 {
    margin: 0;
    font-size: 1.04rem;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: #3e362c;
  }

  .summary textarea,
  input,
  .entry-row textarea {
    width: 100%;
    border: 1px solid #e2d8cb;
    border-radius: 6px;
    padding: 0.45rem 0.55rem;
    background: #fff;
  }

  .summary textarea {
    margin-top: 0.45rem;
  }

  .section-header {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    border-bottom: 1px solid #e8dfd3;
    padding-bottom: 0.35rem;
  }

  .section-header span {
    color: var(--muted);
    font-size: 0.82rem;
  }

  .entries {
    margin-top: 0.7rem;
    display: grid;
    gap: 0.75rem;
  }

  .entry-row {
    padding-bottom: 0.6rem;
    border-bottom: 1px dashed #e9dfd2;
  }

  .entry-head,
  .entry-meta {
    display: grid;
    gap: 0.45rem;
    margin-bottom: 0.45rem;
  }

  .entry-head {
    grid-template-columns: 1fr 1fr;
  }

  .entry-meta {
    grid-template-columns: repeat(3, 1fr);
  }

  .bullets {
    margin-top: 0.7rem;
  }

  .bullet-line {
    display: grid;
    grid-template-columns: auto 1fr auto;
    gap: 0.45rem;
    align-items: center;
    margin-top: 0.45rem;
  }

  .marker {
    color: #685b4b;
    font-size: 1rem;
  }

  .remove-bullet {
    width: 1.9rem;
    height: 1.9rem;
    border: 1px solid #e4c2c2;
    border-radius: 999px;
    background: #fff;
    color: #c02222;
    font-size: 1.1rem;
    line-height: 1;
  }

  .add-bullet {
    margin-top: 0.6rem;
    border: 1px dashed #cdbba4;
    background: #fbf8f2;
    color: #5b4f41;
    border-radius: 6px;
    padding: 0.42rem 0.58rem;
    font-size: 0.86rem;
  }

  .empty {
    margin: 0.45rem 0 0;
    color: var(--muted);
    font-size: 0.9rem;
  }

  .empty-state {
    max-width: 860px;
    margin: 0 auto;
    border: 1px solid var(--line);
    border-radius: 10px;
    background: #fff;
    padding: 1.2rem;
  }

  .empty-state h1 {
    margin: 0;
  }

  .empty-state p {
    color: var(--muted);
  }

  @media (max-width: 760px) {
    .resume-sheet {
      padding: 1.2rem;
    }

    .entry-head,
    .entry-meta,
    .editor-topbar {
      grid-template-columns: 1fr;
      display: grid;
      gap: 0.45rem;
    }

    .editor-topbar {
      justify-content: unset;
    }
  }
</style>

// packages/bakeoff2/app/pages/editor.vue
<template>
  <section class="editor">
    <div class="editor-actions">
      <p v-if="resume" class="dirty-indicator" :class="hasUnsavedChanges ? 'dirty' : 'clean'">
        {{ hasUnsavedChanges ? 'Unsaved changes' : 'All changes saved' }}
      </p>
      <button type="button" class="btn" :disabled="isSaving || !resume" @click="saveResume">
        {{ isSaving ? 'Saving...' : 'Save Resume' }}
      </button>
      <button
        type="button"
        class="btn btn-primary"
        :disabled="isSaving || !resume"
        @click="saveAndPrint"
      >
        {{ isSaving ? 'Saving...' : 'Print' }}
      </button>
      <p v-if="saveError" class="status error">Could not save resume.</p>
    </div>

    <div v-if="resume" class="editor-size-indicator">
      <ResumePrintSheet :resume="resume" mode="indicator" />
    </div>

    <header class="editor-header">
      <p class="kicker">Editor</p>
      <h1 v-if="resume">
        <EditableInlineText
          :model-value="resume.title"
          placeholder="Resume title"
          @update:model-value="onResumeTitleUpdate"
        />
      </h1>
      <h1 v-else>Resume Editor</h1>
      <p v-if="resume">
        <EditableInlineText
          :model-value="resume.summary"
          placeholder="Add overall resume summary"
          @update:model-value="onResumeSummaryUpdate"
        />
      </p>
      <p v-else-if="!resumeId" class="status error">Missing resumeId query param.</p>
    </header>

    <p v-if="pending" class="status">Loading resume...</p>
    <p v-else-if="error" class="status error">Could not load resume.</p>

    <div v-if="resume" class="sections">
      <article v-for="section in resume.sections" :key="section.id" class="section-card">
        <div class="section-header">
          <h2>
            <EditableInlineText
              :model-value="section.title"
              @update:model-value="onSectionTitleUpdate(section.id, $event)"
            />
          </h2>
          <button
            type="button"
            class="btn btn-danger btn-icon"
            aria-label="Remove section"
            title="Remove section"
            @click="removeSection(section.id)"
          >
            x
          </button>
        </div>

        <ul v-if="section.items.length" class="item-list">
          <li v-for="item in section.items" :key="item.id">
            <strong>
              <EditableInlineText
                :model-value="item.label"
                placeholder="Subsection title"
                @update:model-value="onSubsectionTitleUpdate(section.id, item.id, $event)"
              />
            </strong>
            <span>
              ·
              <EditableInlineText
                :model-value="item.value ?? ''"
                placeholder="Add location or subtitle"
                @update:model-value="onSubsectionValueUpdate(section.id, item.id, $event)"
              />
            </span>
            <p>
              <EditableInlineText
                :model-value="item.description ?? ''"
                placeholder="Add subsection description"
                @update:model-value="onSubsectionDescriptionUpdate(section.id, item.id, $event)"
              />
            </p>
          </li>
        </ul>

        <EditableBulletList
          :bullets="section.bullet_points"
          @update="onBulletUpdate(section.id, $event)"
          @remove="onBulletRemove(section.id, $event)"
        />
        <button type="button" class="btn btn-add-bullet" @click="addBulletPoint(section.id)">
          Add bullet point
        </button>
      </article>
    </div>
  </section>
</template>

<script setup lang="ts">
defineOptions({
  name: 'ResumeEditorPage',
});

type SectionItem = {
  id: number;
  section_id: number;
  label: string;
  value: string | null;
  start_date: string | null;
  end_date: string | null;
  location: string | null;
  description: string | null;
  item_order: number;
};

type BulletPoint = {
  id: number;
  section_id: number;
  content: string;
  item_order: number;
};

type Section = {
  id: number;
  resume_id: number;
  title: string;
  item_order: number;
  type: string;
  items: SectionItem[];
  bullet_points: BulletPoint[];
};

type ResumeDetail = {
  id: number;
  user_id: number;
  title: string;
  summary: string;
  created_at: string;
  updated_at: string;
  sections: Section[];
};

const route = useRoute();
const resumeId = computed(() => {
  const raw = route.query.resumeId;
  const parsed = Number(Array.isArray(raw) ? raw[0] : raw);
  return Number.isInteger(parsed) ? parsed : null;
});

const { data, pending, error } = await useAsyncData<ResumeDetail | null>(
  () => `resume-editor-${resumeId.value ?? 'missing'}`,
  () => {
    if (!resumeId.value) {
      return Promise.resolve(null);
    }

    return $fetch<ResumeDetail>(`/api/resumes/${resumeId.value}`);
  },
  {
    server: false,
    immediate: true,
    default: () => null,
  }
);

const resume = computed(() => data.value);
const isSaving = ref(false);
const saveError = ref(false);
const lastSavedSnapshot = ref<ResumeDetail | null>(null);

function cloneResume(value: ResumeDetail) {
  return typeof structuredClone === 'function'
    ? structuredClone(value)
    : JSON.parse(JSON.stringify(value));
}

const hasUnsavedChanges = computed(() => {
  if (!data.value || !lastSavedSnapshot.value) return false;
  return JSON.stringify(data.value) !== JSON.stringify(lastSavedSnapshot.value);
});

watch(
  () => data.value,
  (next, previous) => {
    if (!next || previous) return;
    lastSavedSnapshot.value = cloneResume(next);
  },
  { immediate: true }
);

async function saveResume() {
  if (!resumeId.value || !data.value || isSaving.value) return;

  isSaving.value = true;
  saveError.value = false;

  try {
    await $fetch(`/api/resumes/${resumeId.value}`, {
      method: 'PUT',
      body: data.value,
    });
    lastSavedSnapshot.value = cloneResume(data.value);
    return true;
  } catch {
    saveError.value = true;
    return false;
  } finally {
    isSaving.value = false;
  }
}

async function saveAndPrint() {
  if (!hasUnsavedChanges.value) {
    if (!resumeId.value) return;
    await navigateTo(`/print?resumeId=${resumeId.value}&from=editor`);
    return;
  }

  const saved = await saveResume();
  if (!saved || !resumeId.value) return;

  await navigateTo(`/print?resumeId=${resumeId.value}&from=editor`);
}

function onResumeTitleUpdate(title: string) {
  if (!data.value) return;
  data.value = {
    ...data.value,
    title,
  };
}

function onResumeSummaryUpdate(summary: string) {
  if (!data.value) return;
  data.value = {
    ...data.value,
    summary,
  };
}

function onBulletUpdate(sectionId: number, payload: { id: number; content: string }) {
  if (!data.value) return;

  data.value = {
    ...data.value,
    sections: data.value.sections.map((section) => {
      if (section.id !== sectionId) return section;
      return {
        ...section,
        bullet_points: section.bullet_points.map((bullet) =>
          bullet.id === payload.id ? { ...bullet, content: payload.content } : bullet
        ),
      };
    }),
  };
}

function addBulletPoint(sectionId: number) {
  if (!data.value) return;

  const nextTempId =
    Math.min(
      0,
      ...data.value.sections.flatMap((section) =>
        section.bullet_points.map((bullet) => bullet.id).filter((id) => id <= 0)
      )
    ) - 1;

  data.value = {
    ...data.value,
    sections: data.value.sections.map((section) => {
      if (section.id !== sectionId) return section;
      return {
        ...section,
        bullet_points: [
          ...section.bullet_points,
          {
            id: nextTempId,
            section_id: sectionId,
            content: 'New bullet point',
            item_order: section.bullet_points.length + 1,
          },
        ],
      };
    }),
  };
}

function onBulletRemove(sectionId: number, payload: { id: number }) {
  if (!data.value) return;

  data.value = {
    ...data.value,
    sections: data.value.sections.map((section) => {
      if (section.id !== sectionId) return section;
      const remainingBullets = section.bullet_points
        .filter((bullet) => bullet.id !== payload.id)
        .map((bullet, index) => ({ ...bullet, item_order: index + 1 }));
      return {
        ...section,
        bullet_points: remainingBullets,
      };
    }),
  };
}

function removeSection(sectionId: number) {
  if (!data.value) return;

  const remainingSections = data.value.sections
    .filter((section) => section.id !== sectionId)
    .map((section, index) => ({ ...section, item_order: index + 1 }));

  data.value = {
    ...data.value,
    sections: remainingSections,
  };
}

function onSectionTitleUpdate(sectionId: number, title: string) {
  if (!data.value) return;

  data.value = {
    ...data.value,
    sections: data.value.sections.map((section) =>
      section.id === sectionId ? { ...section, title } : section
    ),
  };
}

function onSubsectionTitleUpdate(sectionId: number, itemId: number, label: string) {
  if (!data.value) return;

  data.value = {
    ...data.value,
    sections: data.value.sections.map((section) => {
      if (section.id !== sectionId) return section;
      return {
        ...section,
        items: section.items.map((item) => (item.id === itemId ? { ...item, label } : item)),
      };
    }),
  };
}

function onSubsectionValueUpdate(sectionId: number, itemId: number, value: string) {
  if (!data.value) return;

  const nextValue = value || null;
  data.value = {
    ...data.value,
    sections: data.value.sections.map((section) => {
      if (section.id !== sectionId) return section;
      return {
        ...section,
        items: section.items.map((item) =>
          item.id === itemId ? { ...item, value: nextValue } : item
        ),
      };
    }),
  };
}

function onSubsectionDescriptionUpdate(sectionId: number, itemId: number, description: string) {
  if (!data.value) return;

  const nextDescription = description || null;
  data.value = {
    ...data.value,
    sections: data.value.sections.map((section) => {
      if (section.id !== sectionId) return section;
      return {
        ...section,
        items: section.items.map((item) =>
          item.id === itemId ? { ...item, description: nextDescription } : item
        ),
      };
    }),
  };
}
</script>

<style scoped>
.editor {
  display: grid;
  gap: 1rem;
}

.editor-actions {
  display: flex;
  align-items: center;
  gap: 0.65rem;
  justify-content: flex-end;
}

.dirty-indicator {
  margin: 0;
  font-size: 0.82rem;
  font-weight: 600;
}

.dirty-indicator.dirty {
  color: #b45309;
}

.dirty-indicator.clean {
  color: #166534;
}

.btn {
  border: 1px solid #cbd5e1;
  background: #fff;
  color: #0f172a;
  border-radius: 0.45rem;
  font-size: 0.85rem;
  font-weight: 600;
  padding: 0.35rem 0.6rem;
  cursor: pointer;
}

.btn:hover {
  border-color: #94a3b8;
}

.btn-primary {
  border-color: #1d4ed8;
}

.btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.editor-size-indicator {
  display: flex;
  justify-content: flex-end;
}

.btn-add-bullet {
  margin-top: 0.5rem;
}

.btn-danger {
  border-color: #fecaca;
  background: #fff5f5;
  color: #b91c1c;
}

.btn-danger:hover {
  border-color: #fca5a5;
  background: #fef2f2;
}

.btn-icon {
  width: 1.7rem;
  height: 1.7rem;
  min-width: 1.7rem;
  padding: 0;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  line-height: 1;
  font-size: 1rem;
  font-weight: 800;
  flex: none;
}

.editor-header {
  padding: 1.2rem;
  border: 1px solid #dbeafe;
  border-radius: 0.9rem;
  background: #fff;
}

.kicker {
  margin: 0 0 0.6rem;
  color: #1d4ed8;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  font-size: 0.75rem;
}

h1 {
  margin: 0;
  font-size: 1.6rem;
}

.editor-header p {
  margin: 0.7rem 0 0;
  color: #334155;
}

.status {
  margin: 0;
  color: #334155;
}

.status.success {
  color: #166534;
}

.status.error {
  color: #b91c1c;
}

.sections {
  display: grid;
  gap: 0.85rem;
}

.section-card {
  background: #fff;
  border: 1px solid #dbeafe;
  border-radius: 0.9rem;
  padding: 1rem;
}

.section-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 0.75rem;
  margin-bottom: 0.6rem;
}

.section-card h2 {
  margin: 0;
  font-size: 1.1rem;
}

.item-list {
  margin: 0;
  padding-left: 1.2rem;
  color: #334155;
}

.item-list p {
  margin: 0.35rem 0 0.75rem;
}
</style>
