// packages/bakeoff1/src/routes/print/+page.svelte
<script lang="ts">
  import type { PageData } from './$types';

  let { data }: { data: PageData } = $props();

  function formatDateRange(startDate: unknown, endDate: unknown) {
    const start = startDate === null || startDate === undefined ? '' : String(startDate).trim();
    const end = endDate === null || endDate === undefined ? '' : String(endDate).trim();
    if (start && end) return `${start} - ${end}`;
    return start || end;
  }
</script>

<main class="print-page">
  <div class="toolbar">
    <button type="button" onclick={() => window.print()}>Print</button>
  </div>

  <article class="resume">
    <h1>{data.resume.title}</h1>

    {#if data.resume.summary?.trim()}
      <section>
        <h2>Professional Summary</h2>
        <p>{data.resume.summary}</p>
      </section>
    {/if}

    {#each data.resume.sections as section (section.id)}
      <section>
        <h2>{section.title}</h2>

        {#if section.items.length > 0}
          {#each section.items as item (item.id)}
            <div class="entry">
              <div class="entry-head">
                <strong>{item.label}</strong>
                <span>{item.value}</span>
              </div>
              <div class="entry-meta">
                <span>{formatDateRange(item.start_date, item.end_date)}</span>
                <span>{item.location}</span>
              </div>
              {#if item.description?.trim()}
                <p>{item.description}</p>
              {/if}
            </div>
          {/each}
        {/if}

        {#if section.bullets.length > 0}
          <ul>
            {#each section.bullets as bullet (bullet.id)}
              {#if bullet.content.trim()}
                <li>{bullet.content}</li>
              {/if}
            {/each}
          </ul>
        {/if}
      </section>
    {/each}
  </article>
</main>

<style>
  .print-page {
    max-width: 850px;
    margin: 0 auto;
    padding: 1rem;
    color: #111;
    background: #fff;
  }

  .toolbar {
    margin-bottom: 1rem;
  }

  button {
    padding: 0.35rem 0.75rem;
    border: 1px solid #bbb;
    background: #fff;
    border-radius: 4px;
  }

  .resume h1 {
    margin: 0 0 0.75rem;
    font-size: 2rem;
  }

  section {
    margin-top: 0.9rem;
  }

  h2 {
    margin: 0 0 0.45rem;
    font-size: 1rem;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    border-bottom: 1px solid #ddd;
    padding-bottom: 0.2rem;
  }

  p {
    margin: 0.3rem 0;
    white-space: pre-wrap;
  }

  .entry {
    margin-bottom: 0.5rem;
  }

  .entry-head,
  .entry-meta {
    display: flex;
    justify-content: space-between;
    gap: 0.5rem;
  }

  ul {
    margin: 0.4rem 0 0;
    padding-left: 1.1rem;
  }

  @media print {
    @page {
      margin: 12mm;
      size: auto;

      @top-center {
        content: '';
      }
      @bottom-center {
        content: '';
      }
    }

    :global(.contents > header),
    :global(.contents > footer) {
      display: none !important;
    }

    .toolbar {
      display: none;
    }

    .print-page {
      max-width: none;
      margin: 0;
      padding: 0;
    }
  }
</style>

// packages/bakeoff2/app/pages/print.vue
<template>
  <section class="print-page">
    <div class="print-actions">
      <NuxtLink class="btn" to="/dashboard">Back</NuxtLink>
      <button type="button" class="btn btn-primary" @click="printResume">Print</button>
    </div>

    <p v-if="pending" class="status">Loading resume...</p>
    <p v-else-if="error" class="status error">Could not load resume.</p>
    <p v-else-if="!resumeId" class="status error">Missing resumeId query param.</p>

    <article v-else-if="resume" class="resume-sheet">
      <h1>{{ resume.title }}</h1>
      <p v-if="resume.summary" class="summary">{{ resume.summary }}</p>

      <section v-for="section in resume.sections" :key="section.id" class="resume-section">
        <h2>{{ section.title }}</h2>

        <ul v-if="section.items.length" class="plain-list">
          <li v-for="item in section.items" :key="item.id">
            <strong>{{ item.label }}</strong>
            <span v-if="item.value"> - {{ item.value }}</span>
            <p v-if="item.description">{{ item.description }}</p>
          </li>
        </ul>

        <ul v-if="section.bullet_points.length" class="plain-list">
          <li v-for="bullet in section.bullet_points" :key="bullet.id">
            {{ bullet.content }}
          </li>
        </ul>
      </section>
    </article>
  </section>
</template>

<script setup lang="ts">
defineOptions({
  name: 'PrintResumePage',
});

type SectionItem = {
  id: number;
  section_id: number;
  label: string;
  value: string | null;
  start_date: string | null;
  end_date: string | null;
  location: string | null;
  description: string | null;
  item_order: number;
};

type BulletPoint = {
  id: number;
  section_id: number;
  content: string;
  item_order: number;
};

type Section = {
  id: number;
  resume_id: number;
  title: string;
  item_order: number;
  type: string;
  items: SectionItem[];
  bullet_points: BulletPoint[];
};

type ResumeDetail = {
  id: number;
  user_id: number;
  title: string;
  summary: string;
  created_at: string;
  updated_at: string;
  sections: Section[];
};

const route = useRoute();
const resumeId = computed(() => {
  const raw = route.query.resumeId;
  const parsed = Number(Array.isArray(raw) ? raw[0] : raw);
  return Number.isInteger(parsed) ? parsed : null;
});

const apiPath = computed(() => (resumeId.value ? `/api/resumes/${resumeId.value}` : null));

const { data, pending, error } = await useFetch<ResumeDetail | null>(apiPath, {
  server: false,
  immediate: true,
  default: () => null,
});

const resume = computed(() => data.value);

function printResume() {
  window.print();
}
</script>

<style scoped>
.print-page {
  display: grid;
  gap: 1rem;
}

.print-actions {
  display: flex;
  gap: 0.5rem;
}

.btn {
  border: 1px solid #cbd5e1;
  background: #fff;
  color: #0f172a;
  border-radius: 0.45rem;
  font-size: 0.85rem;
  font-weight: 600;
  padding: 0.35rem 0.6rem;
  cursor: pointer;
  text-decoration: none;
}

.btn-primary {
  border-color: #1d4ed8;
}

.status {
  margin: 0;
  color: #334155;
}

.status.error {
  color: #b91c1c;
}

.resume-sheet {
  background: #fff;
  border: 1px solid #e2e8f0;
  padding: 1.25rem;
  max-width: 850px;
}

h1 {
  margin: 0;
  font-size: 1.9rem;
  line-height: 1.2;
}

.summary {
  margin: 0.5rem 0 0;
  color: #334155;
}

.resume-section {
  margin-top: 1rem;
}

h2 {
  margin: 0;
  font-size: 1.05rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.plain-list {
  margin: 0.45rem 0 0;
  padding-left: 1.2rem;
}

.plain-list li {
  margin: 0.2rem 0;
}

.plain-list p {
  margin: 0.1rem 0 0.35rem;
}

@media print {
  @page {
    margin: 12mm;
    size: auto;

    @top-center {
      content: '';
    }

    @bottom-center {
      content: '';
    }
  }

  :global(body) {
    background: #fff;
    margin: 0;
  }

  :global(.site-header),
  :global(.site-footer),
  :global(.print-actions) {
    display: none !important;
  }

  :global(.site-main) {
    width: 100% !important;
    margin: 0 !important;
  }

  .resume-sheet {
    border: 0;
    max-width: none;
    padding: 0;
  }
}
</style>
